services:
  postgres:
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER:-unicampus}
      POSTGRES_PASSWORD: ${DB_PASS:-unicampus_secret}
      POSTGRES_DB: ${DB_NAME:-unicampus_erp}

  redis:
    ports:
      - '6379:6379'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      NODE_ENV: development
      PORT: 8081
    ports:
      - '8081:8081'

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
