services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    env_file: ./backend/.env
    environment:
      NODE_ENV: development
      PORT: 8081
    ports:
      - '8081:8081'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    env_file: ./frontend/.env
    environment:
      NODE_ENV: development
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://34.236.107.120:8081/api/v1
      NEXT_PUBLIC_WS_URL: http://34.236.107.120:8081
      BACKEND_INTERNAL_URL: http://backend:8081/api/v1/:path*
      BACKEND_BASE_URL: http://backend:8081
    ports:
      - '3000:3000'
